[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/calendar/*"
  to = "/.netlify/functions/calendar/:splat"
  status = 200
  force = true

[[headers]]
  for = "/calendar/*"
  [headers.values]
    Content-Type = "text/calendar"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"